model:
  alias: pegasus_pubmed
  hf_name: google/pegasus-pubmed
  source_max_length: 512
  target_max_length: 32
  generation:
    num_beams: 8
    max_new_tokens: 32
    min_new_tokens: 4
    no_repeat_ngram_size: 3
